# Generated by Django 5.2.7 on 2025-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('REMINDER_24H', '24-Hour Reminder'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('RESCHEDULE_PROPOSED', 'Reschedule Proposed')], help_text='Type of message/event', max_length=20),
        ),
    ]
