# Generated by Django 5.2.7 on 2025-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('AWAY', 'Away'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', help_text='Current availability status', max_length=20),
        ),
    ]
