# Generated by Django 5.2.8 on 2025-12-03 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professorprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='cancellation_notice_hours',
            field=models.PositiveIntegerField(default=4, help_text='Hours in advance required to cancel/reschedule consultation (0-720)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(720)]),
        ),
    ]
