# Generated by Django 5.2.8 on 2025-11-30 10:51
# apps/professors/migrations/000X_add_rating_cache.py
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professorprofile_status'),  # Update to your latest migration
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]