# Generated by Django 5.2.8 on 2025-12-13 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_add_rating_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorprofile',
            options={'ordering': ['-average_rating', 'user__last_name', 'user__first_name'], 'verbose_name': 'Professor Profile', 'verbose_name_plural': 'Professor Profiles'},
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cached average rating', max_digits=3),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AddIndex(
            model_name='professorprofile',
            index=models.Index(fields=['-average_rating'], name='professor_p_average_7286e3_idx'),
        ),
    ]
