# Generated by Django 5.2.7 on 2025-11-10 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No_Show')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text='Reason for consultation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_notes', models.TextField(help_text="Professor's notes about the consultation")),
                ('student_feedback', models.TextField(blank=True, help_text="Student's feedback")),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_note', to='consultations.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Consultation', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(limit_choices_to={'user_type': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consulation_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='consultations.consultationslot'),
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['professor', 'start_time'], name='consultatio_profess_42d7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['status', 'start_time'], name='consultatio_status_ddfb80_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', 'status'], name='consultatio_student_655bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot', 'status'], name='consultatio_slot_id_4e113b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('slot', 'student')},
        ),
    ]
