# Generated by Django 5.2.7 on 2025-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_setup_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed initial profile setup (role selection)'),
        ),
    ]
