# Generated by Django 5.2.7 on 2025-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID (required for students)', max_length=32, null=True),
        ),
    ]
