# Generated by Django 5.2.7 on 2025-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_review_alter_consultation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_special_request',
            field=models.BooleanField(default=False, help_text='True if booking was made outside standard availability'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled'), ('RESCHEDULE_PROPOSED', 'Reschedule Proposed')], default='PENDING', help_text='Current status of consultation', max_length=20),
        ),
    ]
